### PR TITLE
Fixed Install in readme.md

### PR DESCRIPTION
**Pull request by DavidFrings**
^

### CODE REVIEW

**Review by NeonGamerBot-QK — CHANGES_REQUESTED** [review]
Can you make the cmds not all be in one line and in a multi line code block

**Comment by DavidFrings** [comment]
Now it is multi line code. :)

**Review by NeonGamerBot-QK — APPROVED** [review]
fixed

**Comment by NeonGamerBot-QK** [comment]
LGTM

**Pull request merged**
